<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Get categories
        $categories = DB::table('categories')->pluck('id', 'Category_name');
        
        $products = [
            // مشروبات ساخنة
            [
                'Product_name' => 'شاي عربي',
                'category_id' => $categories['مشروبات ساخنة'] ?? 1,
                'sku' => 'HOT001',
                'barcode' => '111111111111',
                'cost_price' => 1.00,
                'sell_price' => 3.00,
                'stock_qty' => 500,
                'tax_rate' => 15,
                'reorder_point' => 50,
                'wac' => 1.00,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Product_name' => 'شاي اخضر',
                'category_id' => $categories['مشروبات ساخنة'] ?? 1,
                'sku' => 'HOT002',
                'barcode' => '111111111112',
                'cost_price' => 1.50,
                'sell_price' => 4.00,
                'stock_qty' => 300,
                'tax_rate' => 15,
                'reorder_point' => 50,
                'wac' => 1.50,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Product_name' => 'قهوة عربية',
                'category_id' => $categories['مشروبات ساخنة'] ?? 1,
                'sku' => 'HOT003',
                'barcode' => '111111111113',
                'cost_price' => 2.00,
                'sell_price' => 5.00,
                'stock_qty' => 400,
                'tax_rate' => 15,
                'reorder_point' => 50,
                'wac' => 2.00,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Product_name' => 'لاتيه',
                'category_id' => $categories['مشروبات ساخنة'] ?? 1,
                'sku' => 'HOT004',
                'barcode' => '111111111114',
                'cost_price' => 3.00,
                'sell_price' => 8.00,
                'stock_qty' => 200,
                'tax_rate' => 15,
                'reorder_point' => 30,
                'wac' => 3.00,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // مشروبات باردة
            [
                'Product_name' => 'عصير برتقال',
                'category_id' => $categories['مشروبات باردة'] ?? 2,
                'sku' => 'COLD001',
                'barcode' => '222222221111',
                'cost_price' => 2.00,
                'sell_price' => 6.00,
                'stock_qty' => 150,
                'tax_rate' => 15,
                'reorder_point' => 30,
                'wac' => 2.00,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Product_name' => 'عصير ليمون',
                'category_id' => $categories['مشروبات باردة'] ?? 2,
                'sku' => 'COLD002',
                'barcode' => '222222221112',
                'cost_price' => 1.50,
                'sell_price' => 5.00,
                'stock_qty' => 180,
                'tax_rate' => 15,
                'reorder_point' => 30,
                'wac' => 1.50,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Product_name' => 'مياه معدنية',
                'category_id' => $categories['مشروبات باردة'] ?? 2,
                'sku' => 'COLD003',
                'barcode' => '222222221113',
                'cost_price' => 0.50,
                'sell_price' => 1.50,
                'stock_qty' => 1000,
                'tax_rate' => 15,
                'reorder_point' => 100,
                'wac' => 0.50,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Product_name' => 'كولا',
                'category_id' => $categories['مشروبات باردة'] ?? 2,
                'sku' => 'COLD004',
                'barcode' => '222222221114',
                'cost_price' => 1.00,
                'sell_price' => 3.00,
                'stock_qty' => 500,
                'tax_rate' => 15,
                'reorder_point' => 50,
                'wac' => 1.00,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // وجبات رئيسية
            [
                'Product_name' => 'برجر كلاسيك',
                'category_id' => $categories['وجبات رئيسية'] ?? 3,
                'sku' => 'MAIN001',
                'barcode' => '333333331111',
                'cost_price' => 5.00,
                'sell_price' => 15.00,
                'stock_qty' => 50,
                'tax_rate' => 15,
                'reorder_point' => 10,
                'wac' => 5.00,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Product_name' => 'برجر بالجبن',
                'category_id' => $categories['وجبات رئيسية'] ?? 3,
                'sku' => 'MAIN002',
                'barcode' => '333333331112',
                'cost_price' => 6.00,
                'sell_price' => 18.00,
                'stock_qty' => 50,
                'tax_rate' => 15,
                'reorder_point' => 10,
                'wac' => 6.00,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Product_name' => 'ساندوتش دجاج',
                'category_id' => $categories['وجبات رئيسية'] ?? 3,
                'sku' => 'MAIN003',
                'barcode' => '333333331113',
                'cost_price' => 4.00,
                'sell_price' => 12.00,
                'stock_qty' => 60,
                'tax_rate' => 15,
                'reorder_point' => 15,
                'wac' => 4.00,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // وجبات خفيفة
            [
                'Product_name' => 'بطاطس مقلية صغير',
                'category_id' => $categories['وجبات خفيفة'] ?? 4,
                'sku' => 'SNACK001',
                'barcode' => '444444441111',
                'cost_price' => 1.00,
                'sell_price' => 4.00,
                'stock_qty' => 100,
                'tax_rate' => 15,
                'reorder_point' => 20,
                'wac' => 1.00,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Product_name' => 'بطاطس مقلية كبير',
                'category_id' => $categories['وجبات خفيفة'] ?? 4,
                'sku' => 'SNACK002',
                'barcode' => '444444441112',
                'cost_price' => 1.50,
                'sell_price' => 6.00,
                'stock_qty' => 100,
                'tax_rate' => 15,
                'reorder_point' => 20,
                'wac' => 1.50,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Product_name' => 'hot dog',
                'category_id' => $categories['وجبات خفيفة'] ?? 4,
                'sku' => 'SNACK003',
                'barcode' => '444444441113',
                'cost_price' => 2.00,
                'sell_price' => 7.00,
                'stock_qty' => 80,
                'tax_rate' => 15,
                'reorder_point' => 15,
                'wac' => 2.00,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // حلويات
            [
                'Product_name' => 'كيك شوكلاته',
                'category_id' => $categories['حلويات'] ?? 5,
                'sku' => 'SWEET001',
                'barcode' => '555555551111',
                'cost_price' => 3.00,
                'sell_price' => 8.00,
                'stock_qty' => 30,
                'tax_rate' => 15,
                'reorder_point' => 10,
                'wac' => 3.00,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'Product_name' => 'جاتوه vanilla',
                'category_id' => $categories['حلويات'] ?? 5,
                'sku' => 'SWEET002',
                'barcode' => '555555551112',
                'cost_price' => 2.50,
                'sell_price' => 7.00,
                'stock_qty' => 30,
                'tax_rate' => 15,
                'reorder_point' => 10,
                'wac' => 2.50,
                'Status' => 'مفعل',
                'Created_by' => 'System',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('products')->insert($products);
        
        echo "Products seeded successfully!\n";
    }
}
